language: generic
mono: none
dist: bionic
os: linux

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    - sourceline: 'deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial main'

services:
- postgresql
- mysql
env:
  global:
  - MSSQL_SA_PASSWORD="YourStrong!Passw0rd"
  - ACCEPT_EULA=Y
  - MSSQL_PID='developer'
cache:
  directories:
  - $HOME/.local/share/NuGet/
  - $HOME/.nuget

before_script:
- sudo apt-get install -y --no-install-recommends mssql-tools mssql-server dotnet-runtime-2.2 dotnet-sdk-3.1
- sudo /opt/mssql/bin/mssql-conf -n setup accept-eula

script:
 - dotnet restore
 - dotnet build
 - dotnet test
 - cd DicomTypeTranslation && dotnet pack -p:Version=$(fgrep Version ../SharedAssemblyInfo.cs|cut -d'"' -f2|head -n1) -c Release --include-symbols --include-source
 - if [ ! -z "$TRAVIS_TAG"]; then nuget push HIC.DicomTypeTranslation.$TRAVIS_TAG.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${NUGET_KEY}
 