
# https://travis-ci.community/t/dotnet-core-2-2/1216
dist: bionic

branches:
  only:
  - master
  - /^release\/.*$/
  - /^hotfix\/.*$/

language: csharp

mono: none
dotnet: 2.2.203

env:  
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    
script:
  - dotnet restore --no-cache
  - dotnet test -c Release
