
branches:
  only:
  - master
  - /^release\/.*$/
  - /^hotfix\/.*$/

language: csharp
mono: none

env:  
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

matrix:
  include:
    # - name: "Dotnet 2.2 on Bionic Linux"
    #   dist: bionic
    #   dotnet: 2.2.203 # https://travis-ci.community/t/dotnet-core-2-2/1216
    
    #   script:
    #     - dotnet restore --no-cache
    #     - dotnet test -c Release
    - name: "Msbuild on Windows"
      os: windows
      env:
        - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - nuget restore -NoCache
        - msbuild /p:Configuration=Release
