branches:
  only:
  - master
  - /^release\/.*$/
  - /^hotfix\/.*$/

os: windows

language: csharp
mono: none

env:  
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    
script:
 - msbuild DicomTypeTranslation /t:Clean;Build /p:Configuration=Debug
